### ISSUE TITLE
EML Format

### ISSUE THREAD

**Issue by ReDoneX0** [invictus-ir/Microsoft-Extractor-Suite#72]
When I run the Get-Email, I receive the eml in the specified directory, but when I open the email it's blank. However, when I open it Notepad ++ I can read the contents. Anyone, else have this happen? I tried in Outlook and Thunderbird and same result.

**Comment by JoeyInvictus** [comment]
Hi, thanks for opening this issue. I’m encountering the same problem when running the following command:

`get-email -userIds "FortunaHodan@bonacu.onmicrosoft.com" -internetMessageId "<ZH5MFN2H5NU4.5CG7TVE1CCSW2@db3pepf00000765>"`

However, when I place `<ZH5MFN2H5NU4.5CG7TVE1CCSW2@db3pepf00000765>` in a text file named `test.txt` and run the command below, it works as expected:

`get-email -userIds "FortunaHodan@bonacu.onmicrosoft.com" -inputFile .\Output\EmailExport\test.txt`
 
As a workaround, you can place your message ID in a text file and use the `-inputFile` parameter. In the meantime, I will investigate the issue further to determine what might be going wrong.

**Comment by JoeyInvictus** [comment]
I have found the solution and will include it in the next update. In the meantime, you can make the necessary changes to the script yourself if needed.

Navigate to:

`Scripts\Get-Emails.ps1`

Then, update lines 132 and 133 from:
```
$contentUri = "https://graph.microsoft.com/v1.0/users/$userIds/messages/$messageId/\$value"               
Invoke-MgGraphRequest -Uri $contentUri -Method Get -OutputFilePath $filePath
```

to:
```
$contentUri = "https://graph.microsoft.com/v1.0/users/$userIds/messages/" + $messageId + "/`$value"
Invoke-MgGraphRequest -Method GET $contentUri -OutputFilePath $filePath
```

This should resolve the issue.

**Comment by ReDoneX0** [comment]
I made the changes you provided and still received the same outcome.

**Comment by ReDoneX0** [comment]
![image](https://github.com/user-attachments/assets/7ebf56ee-c7cf-4cd9-a6d8-05f0f939fadc)

**Comment by JoeyInvictus** [comment]
mhh strange. I'll investigate further and attempt to reproduce the issue on my end.

![image](https://github.com/user-attachments/assets/84d87e4d-a68f-4a66-b145-f772541be9e9)

**Comment by ReDoneX0** [comment]
![image](https://github.com/user-attachments/assets/b7447aab-e3c1-467a-8aaf-64a6a11e9c9f)

**Comment by ReDoneX0** [comment]
Let me try with just one internet message. I am currently passing a txt file with a list of many.

**Comment by JoeyInvictus** [comment]
Ah, I see. Sorry about that. You also need to modify lines 90 and 91 and apply the same change.

**Comment by ReDoneX0** [comment]
Ok, so that worked when I passed one Internet message ID.

**Comment by ReDoneX0** [comment]
I Updated  90/91 and same result when passing a txt.

**Comment by JoeyInvictus** [comment]
Same result in terms of it working or failing?

**Comment by ReDoneX0** [comment]
I'm sorry it failed as before.

**Comment by ReDoneX0** [comment]
So it works fine when passing one internet message id but when passing the txt it resorts back to the blank eml message.

**Comment by JoeyInvictus** [comment]
Thanks for letting me know will try to see what is going wrong and try to release a small update for it. 

Just making sure did you remove and import the module again? If not and you make changes it won't change untill the module is loaded in again.

**Comment by ReDoneX0** [comment]
I actually didn't, let me try that real quick.

**Comment by JoeyInvictus** [comment]
Perfect :)! Enjoy your weekend will push the change to the Powershell gallery and release page when I release the next update.

**Comment by ReDoneX0** [comment]
You as well!

**Comment by JoeyInvictus** [comment]
Hi, I fixed this in the new update. Feel free to open a new issue if anything is not working.
